
SGRCLOGO=(
'____ ____ _ ___  ____ ____ _ __ _'
'|__, |--< | |__> |___ [__] | | \|'
);

GRCLOGO=(
'  ___ ___ ___ ___   ___ ___ ___ _  _ '
' / __| _ \_ _|   \ / __/ _ \_ _| \| |'
'| (_ |   /| || |) | (_| (_) | || .` |'
' \___|_|_\___|___/ \___\___/___|_|\_|'
);    
BOINCLOGO=(
'___   ______'
' _ \_/  _  _'
'|_|/ \|| || '
'|_|\_/|| ||_'
'___/ \______'
);

OVERVIEW_ICON=(
'  /\  '
' /  \ '
' |__| '
);

SEND_ICON=(
'  /\  '
'  ||  ' 
' ____ '
);

RECEIVE_ICON=(
'  ||  '
'  \/  '
' ____ '
);

TRANSACTIONS_ICON=(
' <--- '
'      '
' ---> '
);

ADDRESSBOOK_ICON=(
' ---- '
' |  | '
' ---- '
);
VOTING_ICON=(
'      '
'   /  '
' \/   '
);
 
ANSI_CLRLINE="\033[K";
ANSI_RESET="\033[0m";

ANSI_BLACK="\033[30m";
ANSI_RED="\033[31m";
ANSI_GREEN="\033[32m";
ANSI_YELLOW="\033[33m";
ANSI_BLUE="\033[34m";
ANSI_MAGENTA="\033[35m";
ANSI_CYAN="\033[36m";
ANSI_WHITE="\033[37m";

ANSI_BG_BLACK="\033[40m";
ANSI_BG_RED="\033[41m";
ANSI_BG_GREEN="\033[42m";
ANSI_BG_BLUE="\033[44m";
ANSI_BG_WHITE="\033[47m";

# Theme :)

THEME_HEADER_BACKG=$ANSI_BG_BLUE;
THEME_HEADER_FOREG=$ANSI_WHITE;

THEME_BACKG=$ANSI_BG_BLACK;
THEME_FOREG=$ANSI_WHITE;

THEME_TEXT="$THEME_BACKG$THEME_FOREG"

