# Display language
LANG="en";

# Time interval between refreshes in seconds
REFRESHINTERVAL=10;




# Command to run gridcoinresearchd
GRCCOMMAND="gridcoinresearchd";

# our temporary files59cf659c649c7db9807ad74f1bcd82812484f5ed360c5b7472d1d0f46204832
TMPDIR="./tmp";
GETINFO="$TMPDIR/getinfo.txt";	# getinfo
GETMININGINFO="$TMPDIR/getmininginfo.txt";	# getmininginfo
LISTTRANSACTIONS="$TMPDIR/listtransactions.txt";	# raw transaction lists
LISTTRANSACTIONS_TXIDS="$TMPDIR/listtransactions-txids.txt"	# transaction txid list
TRANSACTIONS="$TMPDIR/transactions.csv";	# csv with all transaction data
