
# Wallet main page

T_OVERVIEW='Overview';
T_SENDCOINS='Send coins';
T_RECVCOINS='Receive coins';
T_TRANSACTIONS='Transactions'
T_ADDRESSBOOK='Address book';
T_VOTING='Voting';

# Main area texts

T_BALANCE='Balance';
T_STAKE='Stake';
T_UNCONFIRMED='Unconfirmed';

T_TOTAL='Total';

T_BLOCKS='Blocks';
T_DIFFICULTY='Difficulty';
T_NETWEIGHT='Net weight';
T_COINWEIGHT='Coin weight';
T_MAGNITUDE='Magnitude';
T_PROJECT='Project';
T_CPID='CPID';
T_STATUS='Status';

T_CURRENTPOLL='Current poll';
T_CLIENTMESSAGES='Client Messages';

# Loading texts
T_LOADING='Loading';
T_LOADING_WALLET_INFOS='Loading wallet infos';
T_LOADING_WALLET_EINFOS='Loading extra infos';
T_LOADING_TRANSACTIONS='Loading transaction list';
T_LOADING_TRANSACTION_DATA='Loading transaction data';
T_LOADING_FINISHED='Finished';

# Transaction details
T_TRANSACTION_CATEGORY_SENT="Sent";
T_TRANSACTION_CATEGORY_RECEIVED="Received";
T_TRANSACTION_CATEGORY_MINED="Mined";
T_TRANSACTION_CATEGORY_UNKNOWN="Unknown";

T_TRANSACTION_TYPE_INTEREST="Interest";
