# Wallet main page

T_OVERVIEW='Aperçu';
T_SENDCOINS='Envoyer';
T_RECVCOINS='Recevoir';
T_TRANSACTIONS='Transactions';
T_ADDRESSBOOK="Carnet d'adresses";
T_VOTING='Voter';

# Main area texts

T_BALANCE='Balance';
T_STAKE='Stake';
T_UNCONFIRMED='Non-confirmé';

T_TOTAL='Total';

T_BLOCKS='Blocs';
T_DIFFICULTY='Difficulté';
T_NETWEIGHT='Net weight';
T_COINWEIGHT='Coin weight';
T_MAGNITUDE='Magnitude';
T_PROJECT='Projet';
T_CPID='CPID';
T_STATUS='Statut';

T_CURRENTPOLL='Sondage récent';
T_CLIENTMESSAGES='Messages du wallet';

# Loading texts
T_LOADING='Chargement';
T_LOADING_WALLET_INFOS='Chargement des informations du portefeuille';
T_LOADING_WALLET_EINFOS="Chargement d'informations supplémentaires";
T_LOADING_TRANSACTIONS='Chargement de la liste des transactions';
T_LOADING_TRANSACTION_DATA='Chargement des données de transactions';
T_LOADING_FINISHED='Terminé';

# Transaction details
T_TRANSACTION_CATEGORY_SENT="Envoyé";
T_TRANSACTION_CATEGORY_RECEIVED="Reçu";
T_TRANSACTION_CATEGORY_MINED="Miné";
T_TRANSACTION_CATEGORY_UNKNOWN="Inconnu";

T_TRANSACTION_TYPE_INTEREST="Intérêts";
