
# Wallet main page

T_OVERVIEW='Overview';
T_SENDCOINS='Send coins';
T_RECVCOINS='Receive coins';
T_TRANSACTIONS='Address book';
T_VOTING='Voting';

# Main area texts

T_BALANCE='Balance';
T_STAKE='Stake';
T_UNCONFIRMED='Unconfirmed';

T_TOTAL='Total';

T_BLOCKS='Blocks';
T_DIFFICULTY='Difficulty';
T_NETWEIGHT='Net weight';
T_COINWEIGHT='Coin weight';
T_MAGNITUDE='Magnitude';
T_PROJECT='Project';
T_CPID='CPID';
T_STATUS='Status';

T_CURRENTPOLL='Current poll';
T_CLIENTMESSAGES='Client Messages';
