# Wallet main page

T_OVERVIEW='Übersicht';
T_SENDCOINS='Senden';
T_RECVCOINS='Empfangen';
T_TRANSACTIONS='Transaktionen';
T_ADDRESSBOOK='Adressbuch';
T_VOTING='Abstimmen';

# Main area texts

T_BALANCE='Kontostand';
T_STAKE='Stake';
T_UNCONFIRMED='Unbestätigt';

T_TOTAL='Gesamt';

T_BLOCKS='Blöcke';
T_DIFFICULTY='Schwierigkeit';
T_NETWEIGHT='Netzwerkgewicht';
T_COINWEIGHT='Coin Gewicht';
T_MAGNITUDE='Magnitude';
T_PROJECT='Projekt';
T_CPID='CPID';
T_STATUS='Status';

T_CURRENTPOLL='Aktuelle Abstimmung';
T_CLIENTMESSAGES='Client Nachrichten';

# Loading texts
T_LOADING='Lädt';
T_LOADING_WALLET_INFOS='Lade Wallet Infos';
T_LOADING_WALLET_EINFOS='Lade extra Infos';
T_LOADING_TRANSACTIONS='Lade Transaktionsliste';
T_LOADING_TRANSACTION_DATA='Lade Transaktionsdaten';
T_LOADING_FINISHED='Beendet';

# Transaction details
T_TRANSACTION_CATEGORY_SENT="Gesendet";
T_TRANSACTION_CATEGORY_RECEIVED="Empfangen";
T_TRANSACTION_CATEGORY_MINED="Geschürft";
T_TRANSACTION_CATEGORY_UNKNOWN="Unbekannt";

T_TRANSACTION_TYPE_INTEREST="Zinsen";
